spring.application.name=memoria

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/clientes}
spring.datasource.username=${DB_USERNAME:clientes}
spring.datasource.password=${DB_PASSWORD:clientes}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
